export enum CustomerErrors {
    CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
    DUPLICATE_NAME = 'DUPLICATE_NAME',
    EMPTY_NAME = 'EMPTY_NAME',
    EMPTY_EMAIL = 'EMPTY_EMAIL',
    INVALID_EMAIL = 'INVALID_EMAIL',
    EMPTY_PHONE_NUMBER = 'EMPTY_PHONE_NUMBER',
    INVALID_SEARCH = 'INVALID_SEARCH',
}
