export enum AuthErrors {
    DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNAUTHORIZED = 'UNAUTHORIZED',
    EMPTY_EMAIL = 'EMPTY_EMAIL',
    EMPTY_PASSWORD = 'EMPTY_PASSWORD',
    EMPTY_NAME = 'EMPTY_NAME',
}
